# SPDX-License-Identifier: Apache-2.0

set(MISCLIBC_LIBS_DIR "${CMAKE_CURRENT_LIST_DIR}" CACHE STRING "")
mark_as_advanced(MISCLIBC_LIBS_DIR)

function(misclibc_kernel_import_libraries)
	get_property(IMPORTED_MISCLIBC_PROERTY GLOBAL PROPERTY IMPORTED_MISCLIBC)
	if (NOT DEFINED IMPORTED_MISCLIBC_PROERTY)
		set_property(GLOBAL PROPERTY IMPORTED_MISCLIBC TRUE)

		add_subdirectory(${MISCLIBC_LIBS_DIR} misclibc)
	endif()

	get_property(KERNEL_IMPORTED_MISCLIBC_PROERTY GLOBAL PROPERTY KERNEL_IMPORTED_MISCLIBC)
	if (NOT DEFINED KERNEL_IMPORTED_MISCLIBC)
		set_property(GLOBAL PROPERTY KERNEL_IMPORTED_MISCLIBC TRUE)

		set_property(GLOBAL APPEND PROPERTY KERNEL_IMPORTED_LIBS misclibc)
	endif()
endfunction()

function(misclibc_import_libraries)
	get_property(IMPORTED_MISCLIBC_PROERTY GLOBAL PROPERTY IMPORTED_MISCLIBC)
	if(NOT DEFINED IMPORTED_MISCLIBC_PROERTY)
		set_property(GLOBAL PROPERTY IMPORTED_MISCLIBC TRUE)

		add_subdirectory(${MISCLIBC_LIBS_DIR} misclibc)
	endif()
endfunction()
